#!/usr/bin/python3
"""Script to open a special application based on file type."""
import sys
import os
import shutil


def exec_prog(prog, fname):
    """Execute a program on the given file."""
    if os.fork() == 0:
        os.execv(shutil.which(prog), [prog, fname])


EXT_MAP = {
    'pdf': 'atril',
}


if __name__ == '__main__':
    fname = sys.argv[1]
    parts = fname.lower().split('.')
    try:
        prog = EXT_MAP[parts[-1]]
    except KeyError:
        prog = 'vim'
    exec_prog(prog, fname)
